### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by vinyashegde** [GDSC-PHCET/code-recipes#3]
Improve the project's documentation, including the README and comments within the code, to make it more informative for contributors and users.

**Comment by Vibranium1** [comment]
you can assign this to me.

**Comment by vinyashegde** [comment]
Sure go ahead! @Vibranium1

**Comment by Vibranium1** [comment]
@vinyashegde Hey Vinyas, I have submitted my PR, can you look onto it.

**Comment by vinyashegde** [comment]
good work @Vibranium1
